Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,6 +20,9 @@ jobs:
           username: ${{ secrets.EC2_USERNAME }}
           key: ${{ secrets.EC2_PRIVATE_KEY }}
           script: |
+            echo "Creating directory if it doesn't exist"
+            mkdir -p ~/nest-hello-world/ || { echo "Failed to create directory"; exit 1; }
+
             echo "Changing directory to ~/nest-hello-world/"
             cd ~/nest-hello-world/ || { echo "Failed to change directory"; exit 1; }
 
@@ -30,4 +33,3 @@ jobs:
             npm run start || { echo "Failed to start the application"; exit 1; }
 
             echo "Deployment completed successfully"
-
